# -*- coding: utf-8 -*-
"""NLP mini project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yagwxHe1Ns8wwsEIuydG5yc-NqbMQh7J
"""

# 📌 Emotion Classification using NLP (CSV Dataset)

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

# 1. Load Custom CSV Dataset
# 🔹 Replace with your CSV file path (upload to Colab/Jupyter first)
file_path = "/content/tweet_emotions.csv"   # <-- change this
data = pd.read_csv(file_path)

print("✅ Dataset Loaded Successfully")
print("Sample Data:\n", data.head())

# 2. Split Data (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    data["content"], data["sentiment"], test_size=0.2, random_state=42
)

# 3. Vectorize Text (TF-IDF)
vectorizer = TfidfVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# 4. Train Logistic Regression Model
model = LogisticRegression(max_iter=1000)
model.fit(X_train_vec, y_train)

# 5. Predictions
y_pred = model.predict(X_test_vec)

# 6. Evaluation
print("\n✅ Accuracy:", accuracy_score(y_test, y_pred))
print("\n📊 Classification Report:\n", classification_report(y_test, y_pred))

# 7. Test with Custom Inputs
sample_texts = [
    "I am so happy today!",
    "This is terrible",
    "I love this place",
    "I am scared of exams",
    "Wow, I didn’t expect that"
]
sample_vec = vectorizer.transform(sample_texts)
print("\n🔮 Custom Predictions:")
for txt, pred in zip(sample_texts, model.predict(sample_vec)):
    print(f"{txt} --> {pred}")